### PR TITLE
Style

### PR DESCRIPTION
**Pull request by easybe**
Hi

I am interested in contributing to your project. I have some ideas...

I don't want to sound rude, but would it be okay for you to switch to indentations of 4 space? It would be easier on my eyes. If not, I can also learn to live with 2...

Cheers,
Ezra.

### CODE REVIEW

**Comment by axot** [comment]
Could you setup indent size to 2 spaces in Xcode? This save my screen space

**Comment by axot** [comment]
And we should build libevent and openssl inside this project, for now I'm using homebrew built binaries.

**Comment by easybe** [comment]
OK, if you insist in using 2 spaces I will do so too.

But still, I recommend reading for example Linus Torwalds comments on the subject:

https://www.kernel.org/doc/html/v4.10/process/coding-style.html#indentation

Although he is a rather opinionated person, I think he is right with many things, for example:

"(...) if you need more than 3 levels of indentation, you’re screwed anyway, and should fix your program."

If your lines get too long, you should consider breaking them. Traditionally this would be at 80 (or 79) characters, I think nowadays 120 is OK too...

Concerning the `sstpc` binary and dependencies, the currently bundled doesn't work for me, even after fixing the paths with `install_name_tool`. So I agree, we should build it from source. I could help with that, I have some experience in that department. But for now I have a solution which works for me (https://github.com/easybe/isstp/commits/wip).

First I would like to improve the GUI, make it similar to the one of EasySSTP (http://llamedos-software.com/index.php) and other VPN clients...

**Comment by easybe** [comment]
Thanx man! Sorry for benign such a pain in the ass. But, I am just happier contributing to a project following at least some style guidelines...

**Pull request merged**
